### ISSUE TITLE
Tundra does not support fuzzy matching within URLs or Headers

### ISSUE THREAD

**Issue by vasarathbabu** [tylermurry/tundra-fetch#16]
While capturing the actual Tundra profile, After an action was performed on a element in window1 , the element was moved to Window2  due to the action and removed from Window1 by a auto refresh process. 

But while rerunning the captured Tundra profile for testing, the element which is moved to window2 still resides in Window1 with the same state it was captured first time. 

Note: In Window2 the element captured correctly.

**Comment by tylermurry** [comment]
Had an offline discussion with @vasarathbabu to convert this symptom into a workable problem:

Sometimes URLs and headers can contain dynamic data (e.g. current date). Tundra currently only supports fuzzy matching within the request body. An update needs to be made to support this within the URL/Headers so the functionality can be shared across all forms of request inputs.
